---
  - name: Build main server docker image
    become: yes
    docker_image:
      name: "main_server"
      path: "../../main_server"

  - name: Build load balancer docker image
    become: yes
    docker_image:
      name: "load_balancer"
      path: "../../load_balancer"

  - name: Build execution node docker image
    become: yes
    docker_image:
      name: "execution_node"
      path: "../../execution_nodes"
